### ISSUE TITLE
unable to download pretrain models, got 404

### ISSUE THREAD

**Issue by YOULLNEVERWA** [JianpingLin/M-LVC_CVPR2020#2]

**Comment by JianpingLin** [comment]
Our trained models have been uploaded.

**Comment by weihua04** [comment]
> Our trained models have been uploaded.

i downloaded the pretrained model only 2M, then face the mistake,“下载错误”, does anyone face the same problem?

**Comment by JianpingLin** [comment]
@weihua04 I can still download the pretrained models. Please check your network.
