### ISSUE TITLE
UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.

### ISSUE THREAD

**Issue by lwplw** [JianpingLin/M-LVC_CVPR2020#4]
I encountered the error shown in the title when running the test code. I think this should be a problem with tensorflow. My version is: 1.13.1.

Error content：UnimplementedError （see above for traceback）: Generic conv implementation only supports NHWC tensor format for now. [[node flownet2/conv1/Conv2D (defined at .../M-LVC_CVPR2020-master/flownet_models.py:523)]]

It seems that the graph is successfully created, but the evaluation of the tf.nn.conv2d call is not possible. This is somehow related to the fact that this tf.nn.conv2d call is wrapped in a tf.data.Dataset.map call.

Have you encountered any related problems and how did you solve them?

This is the same error I retrieved: https://github.com/tensorflow/tensorflow/issues/26411

Thank you!

**Comment by JianpingLin** [comment]
The code only supports TensorFlow with GPU mode. I guess you may use the CPU mode.

**Comment by gongmm** [comment]
How to slove this error: The GPU Memory is enough
InternalError (see above for traceback): Blas xGEMMBatched launch failed : a.shape=[5,2,3], b.shape=[5,3,810000], m=2, n=810000, k=3, batch_size=5
         [[node MatMul (defined at /data/wangziang/project/advhat/Attack/stn.py:150) ]]
         [[node AddN (defined at /data/wangziang/project/advhat/Attack/stn.py:227) ]]
