### ISSUE TITLE
vimeo-90k

### ISSUE THREAD

**Issue by kepengxu** [JianpingLin/M-LVC_CVPR2020#5]
I download the vimeo-90k dataset, but the dataset only has 7 clips in one video sequence.
in the paper, you set 16 clips for one video.
how to solve this problem?
thank you vary much

**Comment by JianpingLin** [comment]
I downloaded the original videos by myself. But using 7-frames clips is OK too. For better compression performance, you can use other videos with 16 clips to finetune the models.

**Comment by kepengxu** [comment]
> I downloaded the original videos by myself. But using 7-frames clips is OK too. For better compression performance, you can use other videos with 16 clips to finetune the models.

I have download the Vimeo dataset , and find many large scale video in set,
I think should be resized to low-resolution ，but I don't know how to choose the interpolation method. 
can you tell me what method you take, like INTER_CUBIC or INTER_LINEAR
Thank you vary much!
