### ISSUE TITLE
In Residual Autoencoder, the value in the variable bit_string_resi_test is empty

### ISSUE THREAD

**Issue by lwplw** [JianpingLin/M-LVC_CVPR2020#7]
`bit_string_resi_test` corresponds to `self.bit_string_resi` in line 103 of `test.py`. Use the `bls2017ImgCompression_resi_RGB()` function to find the `model.py` file. Check the relevant code to see that `self.bit_string_resi` should be the quantized and binarized residual, so self. The `bit_string_resi` variable should be used when decoding, but I tried to check the value in `bit_string_resi_test` during the test and found that it was `b' '`.

Unlike MVD, `tfc.EntropyBottleneck_gauss()` and `hyperModel `are used in resi. Does this part have any special significance? I did not find the relevant description in the paper.

Hope to get answers from the author, thank you very much

**Comment by lwplw** [comment]
The reason is located. The `tfc.EntropyBottleneck_gauss()` function was used when compressing the residuals, but in the `def compress(self, inputs, input_stddev)` function of the `entropy_models_gauss.py` file (line 461), the author directly returned an empty result:
`return tf.zeros(shape=inputs.shape[:1],dtype=tf.string)`

**Comment by kepengxu** [comment]
I implement the compress and decompress module, but I find bit rate vary large
